# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'basic_app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Clean baseline — no SDKs. Automation will install AppsFlyer here.

end
